#!/bin/bash
#
# proxy.sh — Proxy 配置文件生成
# 业务逻辑由 proxy.lua 驱动，此脚本仅负责生成配置文件
#
# 用法:
#   ./proxy.sh generate [--force]   # 生成 proxy_route.conf + proxy_outbound.txt
#

set -e

MYNET_HOME="${MYNET_HOME:-/etc/mynet}"
PROXY_CONF_DIR="$MYNET_HOME/conf/proxy"
ROLE_CONF="$PROXY_CONF_DIR/proxy_role.conf"
SOURCES_DIR="$PROXY_CONF_DIR/proxy_sources"

# ─────────────────────────────────────────────────────────
# generate_proxy_config
#
# 从 proxy_sources/{chinaip,interip}.txt 生成：
#   proxy_route.conf   — nft 批量加载格式（含 # Gateway 注释）
#   proxy_outbound.txt — 纯 CIDR 列表（供 iptables ipset）
# ─────────────────────────────────────────────────────────
generate_proxy_config() {
    local force="${1:-}"

    # 读取 region + peers
    local region="domestic"
    local peers=""
    if [ -f "$ROLE_CONF" ]; then
        region=$(grep "^NODE_REGION=" "$ROLE_CONF" 2>/dev/null | cut -d'"' -f2 | head -1)
        peers=$(grep "^PROXY_PEERS=" "$ROLE_CONF" 2>/dev/null | cut -d'"' -f2 | head -1)
    fi
    [ -z "$region" ] && region="domestic"

    # 从 GNB route.conf 查找 peer 的 virtual_ip 作为网关
    local gateway=""
    if [ -n "$peers" ]; then
        local node_id
        node_id=$(grep "^NODE_ID=" "$MYNET_HOME/conf/mynet.conf" 2>/dev/null | cut -d'=' -f2 | tr -d '"')
        local route_conf="$MYNET_HOME/driver/gnb/conf/$node_id/route.conf"
        if [ -f "$route_conf" ]; then
            local first_peer
            first_peer=$(echo "$peers" | cut -d',' -f1)
            gateway=$(grep "^${first_peer}|" "$route_conf" | head -1 | cut -d'|' -f2)
        fi
    fi
    [ -z "$gateway" ] && { echo "[ERROR] 无法确定代理网关 IP"; return 1; }

    # 选择 IP 列表（domestic→国际IP走代理, international→国内IP走代理）
    local src_file=""
    if [ "$region" = "domestic" ]; then
        src_file="$SOURCES_DIR/interip.txt"
    else
        src_file="$SOURCES_DIR/chinaip.txt"
    fi
    [ ! -f "$src_file" ] && { echo "[ERROR] IP 列表不存在: $src_file"; return 1; }

    # 检查是否需要重新生成（--force 跳过）
    if [ "$force" != "--force" ] && [ -f "$PROXY_CONF_DIR/proxy_route.conf" ]; then
        local src_mt dst_mt cached_gw
        src_mt=$(stat -c %Y "$src_file" 2>/dev/null || stat -f %m "$src_file" 2>/dev/null || echo 0)
        dst_mt=$(stat -c %Y "$PROXY_CONF_DIR/proxy_route.conf" 2>/dev/null || stat -f %m "$PROXY_CONF_DIR/proxy_route.conf" 2>/dev/null || echo 0)
        cached_gw=$(grep "^# Gateway:" "$PROXY_CONF_DIR/proxy_route.conf" 2>/dev/null | head -1 | sed 's/^# Gateway: //')
        # IP 列表未变 且 网关未变 → 跳过；peer 改变时网关会变，必须重新生成
        if [ "$dst_mt" -ge "$src_mt" ] && [ "$cached_gw" = "$gateway" ]; then
            echo "[INFO] proxy_route.conf 已是最新，跳过"; return 0
        fi
        [ "$cached_gw" != "$gateway" ] && echo "[INFO] 网关已变更 ($cached_gw → $gateway)，重新生成"
    fi

    mkdir -p "$PROXY_CONF_DIR"
    local count=0

    # 生成 proxy_outbound.txt（纯 CIDR，供 iptables ipset）
    grep -v '^#' "$src_file" | grep -v '^$' | grep '/' > "$PROXY_CONF_DIR/proxy_outbound.txt" || true
    count=$(wc -l < "$PROXY_CONF_DIR/proxy_outbound.txt" 2>/dev/null || echo 0)

    # 生成 proxy_route.conf（nft 批量格式）
    {
        echo "# Auto-generated by proxy.sh — do not edit"
        echo "# Gateway: $gateway"
        echo "# Region: $region"
        echo "# Source: $(basename "$src_file")"
        echo "# Count: $count"
        echo "# Generated: $(date '+%Y-%m-%d %H:%M:%S')"
        echo ""
        while IFS= read -r line; do
            [[ "$line" =~ ^# ]] && continue
            [[ -z "$line" ]] && continue
            [[ "$line" == */* ]] || continue
            echo "add element inet mynet_proxy mynet_proxy { $line }"
        done < "$src_file"
    } > "$PROXY_CONF_DIR/proxy_route.conf"

    echo "[INFO] ✓ proxy_route.conf ($count CIDR, region=$region, gw=$gateway)"
}

# ─── 主入口 ───
case "${1:-}" in
    generate|generate_config)
        generate_proxy_config "${2:-}"
        ;;
    *)
        echo "用法: $0 generate [--force]"
        echo ""
        echo "注意: start/stop/status 等操作由 LuCI → proxy.lua 驱动"
        echo "      系统命令由 route_policy.sh 执行"
        exit 1
        ;;
esac
